# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- bash: |
    sudo apt-get update
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    hash -r
    conda config --set always_yes yes --set changeps1 no
    conda update -q conda
    conda info -a
    which conda
    conda --version
    conda env create -f environment.yml
    source $HOME/miniconda/etc/profile.d/conda.sh
    conda activate cait
  displayName: Setup Conda/create environment

- script: |
    conda list env
    pip freeze
    pytest
  displayName: 'pytest'
