name: Collective Actions in Tech
url: https://collectiveactions.tech
description: An archive of all collective actions from workers in the tech industry.
twitter: 
  username: organizejs
  image: assets/images/share-im.jpg
markdown: kramdown
plugins:
  - jekyll-seo-tag
