name: Archive - Collective Action in Tech
url: https://data.collectiveaction.tech
description: An archive of all collective action from workers in the tech industry.
markdown: kramdown
plugins:
  - jekyll-seo-tag
