name: Validator

on:
  # Trigger the workflow on pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up conda
      run: |
        sudo chown -R $USER /usr/share/miniconda
    - name: Install conda environment
      run: |
        conda env create --quiet --file environment.yml
        conda init bash
    - name: Pytest
      run: |
        conda activate cait
        pytest --junitxml=junit/unit-test.xml
    - name: Run update code to check for errors
      run: |
        conda activate cait
        python update.py --auto
